### ISSUE TITLE
Comparisions in Table 2 of the paper

### ISSUE THREAD

**Issue by ayushjain1144** [PQ3D/PQ3D#4]
Hi, Thank you for your very nice work!

I am a bit confused by comparisons with open-vocabulary methods in Table-2: The open-vocabulary method of OpenScene and OpenMask3D use class-agnostic instance mask labels but not class labels; my understanding is that your method also trains with all labels. Doesn't that make PQ3D incomparable to OpenScene/OpenMask3D?

Additionally, do you train the grounding head with instance segmentation labels as well? (i.e. maybe supplying "Chair" as a prompt during training and asking the grounding head to detect "chairs") or is that head only trained on referential grounding datasets? At inference time, for getting predictions for all 200 classes of scannet, I assume PQ3D needs to do an inference over 200 text prompts individually? (i.e. supply chair as prompt, then table and so on -- ofcourse this can be batched). 

Thank you!

**Comment by zhuziyu-edward** [comment]
Thank you for your questions~
1. We have two evaluation settings. Close vocabulary one uses cls head to assign mask with semantic labels(PQ3D w / cls).   Open vocabulary one instead uses language to ground each mask, which means you can use any text instead of fixed 200 class(PQ3D prompt). 
2. Yes. The model is trained on 200 classes, which can also be batched for inference. The scene encoder features are reusable across batches without additional GPU memory usage because the prompt only applies in the query decoder, allowing 200 text prompts to be stacked in a single batch.
